/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as FlyerSlugRouteImport } from './routes/flyer.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminCategoriasRouteImport } from './routes/_authenticated/admin.categorias'
import { Route as AuthenticatedAdminUtilizadoresRouteImport } from './routes/_authenticated/admin.utilizadores'
import { Route as AuthenticatedAdminFolhetosIndexRouteImport } from './routes/_authenticated/admin.folhetos.index'
import { Route as AuthenticatedAdminFolhetosIdRouteImport } from './routes/_authenticated/admin.folhetos.$id'
import { Route as AuthenticatedAdminFolhetosNovoRouteImport } from './routes/_authenticated/admin.folhetos.novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FlyerSlugRoute = FlyerSlugRouteImport.update({
  id: '/flyer/$slug',
  path: '/flyer/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCategoriasRoute =
  AuthenticatedAdminCategoriasRouteImport.update({
    id: '/admin/categorias',
    path: '/admin/categorias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUtilizadoresRoute =
  AuthenticatedAdminUtilizadoresRouteImport.update({
    id: '/admin/utilizadores',
    path: '/admin/utilizadores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFolhetosIndexRoute =
  AuthenticatedAdminFolhetosIndexRouteImport.update({
    id: '/admin/folhetos/',
    path: '/admin/folhetos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFolhetosIdRoute =
  AuthenticatedAdminFolhetosIdRouteImport.update({
    id: '/admin/folhetos/$id',
    path: '/admin/folhetos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFolhetosNovoRoute =
  AuthenticatedAdminFolhetosNovoRouteImport.update({
    id: '/admin/folhetos/novo',
    path: '/admin/folhetos/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/favoritos': typeof FavoritosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/flyer/$slug': typeof FlyerSlugRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/utilizadores': typeof AuthenticatedAdminUtilizadoresRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/folhetos/$id': typeof AuthenticatedAdminFolhetosIdRoute
  '/admin/folhetos/novo': typeof AuthenticatedAdminFolhetosNovoRoute
  '/admin/folhetos/': typeof AuthenticatedAdminFolhetosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/favoritos': typeof FavoritosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/flyer/$slug': typeof FlyerSlugRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/utilizadores': typeof AuthenticatedAdminUtilizadoresRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/folhetos/$id': typeof AuthenticatedAdminFolhetosIdRoute
  '/admin/folhetos/novo': typeof AuthenticatedAdminFolhetosNovoRoute
  '/admin/folhetos': typeof AuthenticatedAdminFolhetosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/favoritos': typeof FavoritosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/flyer/$slug': typeof FlyerSlugRoute
  '/_authenticated/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/_authenticated/admin/utilizadores': typeof AuthenticatedAdminUtilizadoresRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/folhetos/$id': typeof AuthenticatedAdminFolhetosIdRoute
  '/_authenticated/admin/folhetos/novo': typeof AuthenticatedAdminFolhetosNovoRoute
  '/_authenticated/admin/folhetos/': typeof AuthenticatedAdminFolhetosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/biblioteca'
    | '/favoritos'
    | '/reset-password'
    | '/flyer/$slug'
    | '/admin/categorias'
    | '/admin/utilizadores'
    | '/admin/'
    | '/admin/folhetos/$id'
    | '/admin/folhetos/novo'
    | '/admin/folhetos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/biblioteca'
    | '/favoritos'
    | '/reset-password'
    | '/flyer/$slug'
    | '/admin/categorias'
    | '/admin/utilizadores'
    | '/admin'
    | '/admin/folhetos/$id'
    | '/admin/folhetos/novo'
    | '/admin/folhetos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/biblioteca'
    | '/favoritos'
    | '/reset-password'
    | '/flyer/$slug'
    | '/_authenticated/admin/categorias'
    | '/_authenticated/admin/utilizadores'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/folhetos/$id'
    | '/_authenticated/admin/folhetos/novo'
    | '/_authenticated/admin/folhetos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BibliotecaRoute: typeof BibliotecaRoute
  FavoritosRoute: typeof FavoritosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  FlyerSlugRoute: typeof FlyerSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flyer/$slug': {
      id: '/flyer/$slug'
      path: '/flyer/$slug'
      fullPath: '/flyer/$slug'
      preLoaderRoute: typeof FlyerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/categorias': {
      id: '/_authenticated/admin/categorias'
      path: '/admin/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/utilizadores': {
      id: '/_authenticated/admin/utilizadores'
      path: '/admin/utilizadores'
      fullPath: '/admin/utilizadores'
      preLoaderRoute: typeof AuthenticatedAdminUtilizadoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/folhetos/': {
      id: '/_authenticated/admin/folhetos/'
      path: '/admin/folhetos'
      fullPath: '/admin/folhetos/'
      preLoaderRoute: typeof AuthenticatedAdminFolhetosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/folhetos/$id': {
      id: '/_authenticated/admin/folhetos/$id'
      path: '/admin/folhetos/$id'
      fullPath: '/admin/folhetos/$id'
      preLoaderRoute: typeof AuthenticatedAdminFolhetosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/folhetos/novo': {
      id: '/_authenticated/admin/folhetos/novo'
      path: '/admin/folhetos/novo'
      fullPath: '/admin/folhetos/novo'
      preLoaderRoute: typeof AuthenticatedAdminFolhetosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminCategoriasRoute: typeof AuthenticatedAdminCategoriasRoute
  AuthenticatedAdminUtilizadoresRoute: typeof AuthenticatedAdminUtilizadoresRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminFolhetosIdRoute: typeof AuthenticatedAdminFolhetosIdRoute
  AuthenticatedAdminFolhetosNovoRoute: typeof AuthenticatedAdminFolhetosNovoRoute
  AuthenticatedAdminFolhetosIndexRoute: typeof AuthenticatedAdminFolhetosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminCategoriasRoute: AuthenticatedAdminCategoriasRoute,
  AuthenticatedAdminUtilizadoresRoute: AuthenticatedAdminUtilizadoresRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminFolhetosIdRoute: AuthenticatedAdminFolhetosIdRoute,
  AuthenticatedAdminFolhetosNovoRoute: AuthenticatedAdminFolhetosNovoRoute,
  AuthenticatedAdminFolhetosIndexRoute: AuthenticatedAdminFolhetosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BibliotecaRoute: BibliotecaRoute,
  FavoritosRoute: FavoritosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  FlyerSlugRoute: FlyerSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
